/*************************************************************************

 SourceName         :  sigint.c                                       
Description           : This program demonstrates the working of a SIGINT. SIGINT generated by entering CTRL+C                               


 Compile and execute :                                                               
                To Compile The Program  :  #gcc –o sigint sigint.c
                To Execute The Program   : #./sigint

***************************************************************************/ 
/*--------------------------------------- HEADER FILES ---------------------------------------------*/

#include<stdio.h>
#include<sys/types.h>
#include<sys/ipc.h>
#include<sys/errno.h>
#include<sys/signal.h>

/*-----------------------------------------------------------------------------------------------------------*/

                                            
int flag; 



void sigint_handler()                                                             /*------------------------------------ FUNCTION DEFINITION ------------------------------------*/
{
	printf("\n user defined SIGINT handler invoked to handle CTRL C. \n");
	flag=1;
	return;
}


int main()                                                       /* Start of main()                                                    */
{
	printf("\n Pressr Ctrl+c Within 5 Seconds To Generate Signal\n");
	signal(SIGINT,sigint_handler);
	sleep(5);
	if (flag==0)
 		printf("\n SIGINT not generated by the user !!!\n");
}


/*************************************************************************/

